### ISSUE TITLE
Error while refreshing data on the AKS dashboard

### ISSUE THREAD

**Issue by Jakar2** [Azure/ccodashboard#120]
**Describe the bug**
I was able to install the Infrastructure and Governance dashboard, but when it comes to the AKS dashboard, I have not been successful in installing it. The bug is with the refresh stage, where there is an error somewhere in the M Code.

**To Reproduce**
1. Go to 'ccodashboard\dashboards\CCODashboard-AKS '
2. Open 'CCO AKS Dashboard 5.1'
3. Click 'Refresh All'

**Expected behavior**
Data is expected to be fetched, which it actually is, as I can see it in the advanced editor, but the overall refresh fails, as can be seen in the screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/70937159/93481472-e4122f00-f8fe-11ea-99d7-a8879a1962bc.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - App: PowerBI Desktop 
 - Version [N/A]

[Session log](https://github.com/Azure/ccodashboard/files/5239607/aks.txt)

**Additional context**

**Comment by josunefon** [comment]
Hi @Jakar2 the report needs to be updated because it was developed with an old Power BI version.  You can fix manually this issue selecting "upgrade report". I verified that all the API queries are working properly
![image](https://user-images.githubusercontent.com/39730064/94275428-3c70ae80-ff47-11ea-90d4-752ad48bc925.png)

I will release a new template version ASAP
