### ISSUE TITLE
CCO Azure Governance Dashboard Version 2.2 Update not listing China region 

### ISSUE THREAD

**Issue by amanjeetsingh** [Azure/ccodashboard#134]
**Describe the bug**
China region is not listed in the dropdown in v2.2 of CCO dashboard (see screenshot below)

**To Reproduce**
1. Download v2.2 of CCO Governance Dashboard 
2. Open in the template in Power BI and then configure connection. 
3. The drop down does not list China region. 

**Expected behavior**
China region must be listed so that we can run this report for subscriptions based out of China region.

**Screenshots**
![image](https://user-images.githubusercontent.com/7122931/100175256-215bf400-2f22-11eb-81d4-42a10e58baa8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josunefon** [comment]
Hi @amanjeetsingh,

Currently China is not listed because we've no access to China datacenters to test if the dashboard works well or not. You can easily adapt the dashboard to add a new URL and allow China APIs to be retrieved. 

Just follow these steps:

- Add "China" as a new option:

![image](https://user-images.githubusercontent.com/39730064/101013930-53dea000-3565-11eb-8c52-8912d7fdaf55.png)
 

- And add the management API URL:

![image](https://user-images.githubusercontent.com/39730064/101014075-91432d80-3565-11eb-85af-d4a49923c154.png)

- and here the graph API URL:

![image](https://user-images.githubusercontent.com/39730064/101014119-a750ee00-3565-11eb-8061-2ede6db0f922.png)
