### ISSUE TITLE
Connecting into Azure Service account?

### ISSUE THREAD

**Issue by iukea1** [Azure/ccodashboard#147]
Hello,

I am trying to get this to work in PowerBI online. 

My goal is to have multiple dashboards for each one of our Azure Tenants and have the dashboards refresh every 24 hours 

What / how would be the best way to go about doing this?

**Comment by josunefon** [comment]
Currently using rest/graph API web requests in powerbi desktop there's no option to use service accounts because it's not supported for authentication in the current model.

For autorefresh you can try with direct query sources: https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh.

For PowerBI online you'll need to rebuild the queries and find which authentication method supports authentication using SPN
