### ISSUE TITLE
You can't schedule refresh for this dataset because the following data sources currently don't support refresh

### ISSUE THREAD

**Issue by J4YDH-73** [Azure/ccodashboard#151]
Known issue with remediation? Please advise

Unable to schedule refresh (data sources currently don't support refresh) https://github.com/Azure/ccodashboard/discussions/150

**Comment by iukea1** [comment]
Known issue..... You have to re code the whole dashboard it is a biiiiiiiiitch

**Comment by josunefon** [comment]
Sorry but currently autorefresh is not supported, it will require a recode of almost all the queries. This is in roadmap for future releases. Currently only directquery datasources are supported for [auto-refresh](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh#authoring-reports-with-automatic-page-refresh-in-power-bi-desktop)

**Comment by iukea1** [comment]
Please tell Microsoft's powerBI team to make bearr tokens easier.

**Comment by J4YDH** [comment]
Time and discipline would be better spent than money.

If you look at the Power BI appsource you will find the same reports which have the key requirement for explicit authorisation from your Administrator. The ccodashboard custom connection appeared to give access to all API data including the recently deprecated Defender URLs. - The tutorials supplied highlighted Microsofts requirement for security. Otherwise why spend years deploying expensive, configuration intensive infra when you can circumnavigate it all and drain all details without administrator consent? - It is vital that everyone involved follows the latest knowledge and training on docs.microsoft.com and preferably build internal secure data pipelines rather than using a quick fix that may be old or worse, exposing sensitive data. - Good Luck

**Comment by dualphone** [comment]
Is there any update or work around for this yet ?
