### ISSUE TITLE
Filter on Networking tab looking for "Cristian Edwards" subscription...

### ISSUE THREAD

**Issue by imightbelosthere** [Azure/ccodashboard#152]
**Describe the bug**
Data on Azure VNETs and Subnets doesn't show up properly.

**To Reproduce**
Use the Infra Dashboard and check the filter on the Virtual Networks visualization and it states that's filtering by "Cristian Edwards" subscription

**Expected behavior**
VNETs to be properly listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/74044932/109114388-d8dcee00-773d-11eb-9f65-9eab89f50227.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
- PowerBI Desktop

Can't remove the filter somehow...

**Comment by josunefon** [comment]
Hi @imightbelosthere ,

That's weird because the filter is applied at visual level, and it comes from another page 

![image](https://user-images.githubusercontent.com/39730064/109172428-0c8e3700-7783-11eb-916f-b7bead52b1ed.png)

If we check the filters blade nothing is being applied.

![image](https://user-images.githubusercontent.com/39730064/109172624-452e1080-7783-11eb-8a7f-94f369e3d41f.png)

I'll upload a new version, but on the meantime if you want to fix this quickly you can recreate the visual and no filters will be applied.
