### ISSUE TITLE
Multiple Login prompts for Graph API

### ISSUE THREAD

**Issue by eosho** [Azure/ccodashboard#47]
**Describe the bug**
When performing a refresh for all data, there seems to always be a continuous prompt to login to the Graph API which becomes a pain when you are prompted about 3+ times. What I have done is login once, cancel every other login prompts (which in turn messes up the refresh) then do a new refresh which gets all the data.

**To Reproduce**
1. Performing a refresh within a customers tenant (non Microsoft internal tenant)
2. Click on the refresh icon
3. Wait for the refresh for Service Principal data
4. After the initial prompt to login to the graph API, you will notice multiple prompt attempts.

**Expected behavior**
Similar to logging in to the management.azure.com API, logging in using the Graph API should only be a one time prompt.

**Screenshots**
N/A (I can do a remote session)

**Desktop (please complete the following information):**
 - Power BI Desktop (October release)

**Comment by josunefon** [comment]
Hi @eosho, 

Currently there's no solution for this bug because it's something related with the product. We're working to solve this with PG support and we're also trying see if creating a custom connector we can avoid the two requests for credentials.

Here you have an other open issue where you can track the progress: https://community.powerbi.com/t5/Issues/Sign-in-pop-up-in-PowerBI-desktop/idc-p/747269#M46587

**Comment by eosho** [comment]
@josunefon thanks for the info. I will track the ticket you opened in the Power BI community.
