### ISSUE TITLE
Show CPU and RAM for VMs

### ISSUE THREAD

**Issue by eosho** [Azure/ccodashboard#69]
I have a request from a large customer to show CPU and RAM data for VMs. Don't know if this would be a overkill. Told them Azure Advisor already tells them when a resource is being underutilized.

**Comment by josunefon** [comment]
We're not planning to include the RAM or CPU for the VMs because this information is already included showing the family of the VM.
![image](https://user-images.githubusercontent.com/39730064/74857313-cae2d900-5343-11ea-94fe-402dea7cedf0.png)

This dashboard is not a real time monitoring tool, as you say, with the advisor recommendations it's enough to detect which machines are being underutilized. But if your customer still wants to see this, you can request this data creating a custom extension where you can obtain this data from a log analytics workspace API request. (We're using something similar in the AKS CCO Dashboard)
