### ISSUE TITLE
Cannot set scheduled refresh for dataset in power bi cloud

### ISSUE THREAD

**Issue by eagleeyethinker** [Azure/ccodashboard#91]
The main dashboard CCO Power BI Dashboard looks great. 
Is there is a way to set scheduled refresh for dataset in power bi?
See screenshot as seen in power bi cloud.(https://app.powerbi.com/groups/me/settings/datasets)

![image](https://user-images.githubusercontent.com/7471305/80765717-afe5cf80-8b11-11ea-94f2-21386c1d2058.png)

**Comment by prashantgoel82** [comment]
Hi Satish,

By any chance were you able to got the solution for Scheduled refresh for CCO dashboard in Power BI service?
Till now I was refreshing the dataset in PBI Desktop, but I need to do it in PBI service but got stuck there due to this Dynamic dataset.

Any help would be really great!

Thanks,
Prashant
